# HTTP 跳转 HTTPS
server {
    listen 80;
    # server_name 192.168.1.100;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    # server_name 192.168.1.100;

    ssl_certificate /etc/nginx/ssl/self.crt;
    ssl_certificate_key /etc/nginx/ssl/self.key;

    # 视频流代理配置
    location /camera/ {
        proxy_pass http://host.docker.internal:5002;
    }

    # WebSocket代理配置
    location /socket.io/ {
        proxy_pass http://host.docker.internal:5001;
        # 这三行websocket代理必备
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # 可选则配置，只是为了保留客户端的真实ip、协议等信息
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 前端静态文件配置
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;  # 支持 React Router
    }
}